apiVersion: v1
kind: Service
metadata:
  name: classic-service
  annotations:
    kubernetes.io/elb.class: union
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
